services:
  nodecast-tv:
    image: nodecast-tv:local
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodecast-tv
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000 # Internal container port
